require('dotenv').config();
const express=require('express');
const http=require('http');
const path=require('path');
const cookieParser=require('cookie-parser');
const jwt=require('jsonwebtoken');
const bcrypt=require('bcryptjs');
const {Pool}=require('pg');
const {Server}=require('socket.io');
const Razorpay=require('razorpay');
const crypto=require('crypto');

const PORT=Number(process.env.PORT||3000);
const JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_NOW';
const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:true,credentials:true}});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(express.static(path.join(__dirname,'public')));

async function q(text,params=[]){const r=await pool.query(text,params);return r.rows;}
async function one(text,params=[]){const r=await pool.query(text,params);return r.rows[0];}
async function init(){
 await q(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'student',plan TEXT,membership_status TEXT NOT NULL DEFAULT 'inactive',membership_expires TIMESTAMPTZ,age_band TEXT NOT NULL DEFAULT 'adult',guardian_name TEXT,guardian_email TEXT,guardian_consent BOOLEAN NOT NULL DEFAULT FALSE,terms_accepted_at TIMESTAMPTZ,privacy_accepted_at TIMESTAMPTZ,safety_accepted_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_login TIMESTAMPTZ);`);
 await q(`CREATE TABLE IF NOT EXISTS rooms(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT,duration INTEGER NOT NULL DEFAULT 50,camera_required BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
 await q(`CREATE TABLE IF NOT EXISTS sessions(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),room_id INTEGER REFERENCES rooms(id),started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ended_at TIMESTAMPTZ,seconds INTEGER NOT NULL DEFAULT 0);`);
 await q(`CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),plan TEXT NOT NULL,amount INTEGER NOT NULL,provider TEXT,provider_order_id TEXT,provider_payment_id TEXT,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
 await q(`CREATE TABLE IF NOT EXISTS reports(id SERIAL PRIMARY KEY,reporter_user_id INTEGER REFERENCES users(id),room_id INTEGER REFERENCES rooms(id),category TEXT NOT NULL,details TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),status TEXT NOT NULL DEFAULT 'open',admin_note TEXT);`);
 await q(`CREATE TABLE IF NOT EXISTS help_requests(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),category TEXT NOT NULL,subtype TEXT,details TEXT NOT NULL,preferred_contact TEXT,consent BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),status TEXT NOT NULL DEFAULT 'open',admin_note TEXT);`);
 const admin=await one(`SELECT id FROM users WHERE role='admin' LIMIT 1`);
 if(!admin){const email=(process.env.ADMIN_EMAIL||'admin@brsdigitallibrary.com').toLowerCase();const pw=process.env.ADMIN_PASSWORD||'CHANGE_ME_NOW';const hash=bcrypt.hashSync(pw,12);await q(`INSERT INTO users(name,email,password_hash,role,membership_status,age_band) VALUES($1,$2,$3,'admin','active','adult')`,['BRS Administrator',email,hash]);}
 const rc=await one(`SELECT COUNT(*)::int c FROM rooms`); if(!rc.c){const rooms=[['Camera Study Hall','Camera-on • quiet • individual work',50,true],['Focus Room','Camera optional • deep work',90,false],['Morning Accountability','Start together • cameras on',60,true],['Night Study Club','Evening learners • quiet room',120,false],['Exam Sprint','High-focus • timed blocks',45,false],['Silent Camera Room','No chat • cameras on',50,true]];for(const r of rooms)await q(`INSERT INTO rooms(name,description,duration,camera_required) VALUES($1,$2,$3,$4)`,r);}
}
function signToken(u){return jwt.sign({id:u.id,role:u.role,email:u.email},JWT_SECRET,{expiresIn:'7d'});}
function auth(req,res,next){try{const t=req.cookies.brs_token;if(!t)throw 0;req.user=jwt.verify(t,JWT_SECRET);next();}catch{return res.status(401).json({error:'Authentication required'});}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Admin access required'});next();}
async function safeUser(id){return one(`SELECT id,name,email,phone,role,plan,membership_status,membership_expires,age_band,guardian_name,guardian_email,guardian_consent,created_at,last_login FROM users WHERE id=$1`,[id]);}
function activeMembership(u){return u&&u.membership_status==='active'&&(!u.membership_expires||new Date(u.membership_expires)>new Date());}
function addMonths(d,m){const x=new Date(d);x.setMonth(x.getMonth()+m);return x.toISOString();}
const roomPeers=new Map();
function roomCounts(){const o={};for(const [id,s] of roomPeers)o[id]=s.size;return o;}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'BRS Digital Library'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,phone,password,ageBand,guardianName,guardianEmail,guardianConsent,termsAccepted,privacyAccepted,safetyAccepted}=req.body||{};if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email and password (8+ characters) are required'});if(ageBand!=='adult')return res.status(400).json({error:'The public pilot currently accepts adults (18+) only. Minor/guardian onboarding will be enabled after dedicated verification and legal review.'});if(!termsAccepted||!privacyAccepted||!safetyAccepted)return res.status(400).json({error:'You must accept the Terms, Privacy Notice and Community Safety Rules.'});const hash=bcrypt.hashSync(password,12);const u=await one(`INSERT INTO users(name,email,phone,password_hash,age_band,terms_accepted_at,privacy_accepted_at,safety_accepted_at) VALUES($1,$2,$3,$4,'adult',NOW(),NOW(),NOW()) RETURNING id`,[name.trim(),email.trim().toLowerCase(),phone?.trim()||'',hash]);const user=await safeUser(u.id);res.cookie('brs_token',signToken(user),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*86400000});res.json({user});}catch(e){if(String(e.message).includes('duplicate'))return res.status(409).json({error:'Email is already registered'});res.status(500).json({error:'Registration failed'});}});
app.post('/api/auth/login',async(req,res)=>{const email=(req.body?.email||'').trim().toLowerCase();const user=await one(`SELECT * FROM users WHERE email=$1`,[email]);if(!user||!bcrypt.compareSync(req.body?.password||'',user.password_hash))return res.status(401).json({error:'Incorrect email or password'});await q(`UPDATE users SET last_login=NOW() WHERE id=$1`,[user.id]);const u=await safeUser(user.id);res.cookie('brs_token',signToken(u),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*86400000});res.json({user:u});});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('brs_token');res.json({ok:true});});
app.get('/api/auth/me',auth,async(req,res)=>res.json({user:await safeUser(req.user.id)}));
app.get('/api/auth/socket-token',auth,async(req,res)=>res.json({token:signToken(await safeUser(req.user.id))}));
app.get('/api/rooms',async(req,res)=>{const rooms=await q(`SELECT * FROM rooms WHERE active=true ORDER BY id`);res.json(rooms.map(r=>({...r,participants:roomPeers.get(String(r.id))?.size||0})));});
app.get('/api/dashboard',auth,async(req,res)=>{const u=await safeUser(req.user.id);const totals=await one(`SELECT COALESCE(SUM(seconds),0)::int seconds,COUNT(*)::int sessions FROM sessions WHERE user_id=$1 AND ended_at IS NOT NULL`,[u.id]);const today=await one(`SELECT COALESCE(SUM(seconds),0)::int seconds FROM sessions WHERE user_id=$1 AND started_at::date=CURRENT_DATE`,[u.id]);const recent=await q(`SELECT s.*,r.name room_name FROM sessions s LEFT JOIN rooms r ON r.id=s.room_id WHERE s.user_id=$1 ORDER BY s.id DESC LIMIT 10`,[u.id]);res.json({user:u,totalSeconds:totals.seconds,todaySeconds:today.seconds,sessions:totals.sessions,recent});});
app.post('/api/sessions/start',auth,async(req,res)=>{const room=await one(`SELECT * FROM rooms WHERE id=$1 AND active=true`,[req.body?.roomId]);if(!room)return res.status(404).json({error:'Room not found'});if(!activeMembership(await safeUser(req.user.id)))return res.status(402).json({error:'Active membership required'});const s=await one(`INSERT INTO sessions(user_id,room_id) VALUES($1,$2) RETURNING id`,[req.user.id,room.id]);res.json({sessionId:s.id});});
app.post('/api/sessions/end',auth,async(req,res)=>{const s=await one(`SELECT * FROM sessions WHERE id=$1 AND user_id=$2 AND ended_at IS NULL`,[req.body?.sessionId,req.user.id]);if(!s)return res.status(404).json({error:'Session not found'});const sec=Math.max(0,Math.min(Number(req.body?.seconds)||0,86400));await q(`UPDATE sessions SET ended_at=NOW(),seconds=$1 WHERE id=$2`,[sec,s.id]);res.json({ok:true});});
app.post('/api/help-request',auth,async(req,res)=>{const {category,subtype,details,preferredContact,consent}=req.body||{};const allowed=['medical','academic_counselling','academic_help','motivation'];if(!allowed.includes(category)||!details?.trim()||!consent)return res.status(400).json({error:'Please select a valid help category, describe your request and provide consent.'});if(category==='medical'&&details.trim().length<10)return res.status(400).json({error:'Please provide enough information for the medical helpdesk to review your request.'});await q(`INSERT INTO help_requests(user_id,category,subtype,details,preferred_contact,consent) VALUES($1,$2,$3,$4,$5,$6)`,[req.user.id,category,subtype||'',details.trim().slice(0,5000),preferredContact?.trim()||'',!!consent]);res.json({ok:true,message:'Your request has been submitted to the BRS Helpdesk.'});});
app.get('/api/my-help-requests',auth,async(req,res)=>res.json(await q(`SELECT id,category,subtype,details,preferred_contact,created_at,status,admin_note FROM help_requests WHERE user_id=$1 ORDER BY id DESC LIMIT 20`,[req.user.id])));
app.post('/api/report',auth,async(req,res)=>{const {roomId,category,details}=req.body||{};const allowed=['recording','harassment','sexual_content','impersonation','privacy','child_safety','copyright','other'];if(!allowed.includes(category)||!details?.trim())return res.status(400).json({error:'Valid category and details are required'});await q(`INSERT INTO reports(reporter_user_id,room_id,category,details) VALUES($1,$2,$3,$4)`,[req.user.id,roomId||null,category,details.trim().slice(0,4000)]);res.json({ok:true,message:'Report submitted to BRS administration.'});});
app.post('/api/admin/membership',auth,admin,async(req,res)=>{const months=req.body?.plan==='quarterly'?3:1;const u=await one(`SELECT * FROM users WHERE id=$1`,[req.body?.userId]);if(!u)return res.status(404).json({error:'User not found'});const expiry=addMonths(new Date(),months);await q(`UPDATE users SET plan=$1,membership_status='active',membership_expires=$2 WHERE id=$3`,[months===3?'quarterly':'monthly',expiry,u.id]);res.json({user:await safeUser(u.id)});});
app.get('/api/admin/users',auth,admin,async(req,res)=>res.json(await q(`SELECT u.id,u.name,u.email,u.phone,u.plan,u.membership_status,u.membership_expires,u.age_band,u.guardian_consent,u.created_at,COALESCE(SUM(s.seconds),0)::int study_seconds FROM users u LEFT JOIN sessions s ON s.user_id=u.id WHERE u.role='student' GROUP BY u.id ORDER BY u.id DESC`)));
app.get('/api/admin/reports',auth,admin,async(req,res)=>res.json(await q(`SELECT r.*,u.name reporter_name,u.email reporter_email,rm.name room_name FROM reports r LEFT JOIN users u ON u.id=r.reporter_user_id LEFT JOIN rooms rm ON rm.id=r.room_id ORDER BY r.id DESC`)));
app.get('/api/admin/help-requests',auth,admin,async(req,res)=>res.json(await q(`SELECT h.*,u.name user_name,u.email user_email,u.phone FROM help_requests h LEFT JOIN users u ON u.id=h.user_id ORDER BY h.id DESC`)));
app.patch('/api/admin/help-requests/:id',auth,admin,async(req,res)=>{await q(`UPDATE help_requests SET status=$1,admin_note=$2 WHERE id=$3`,[req.body?.status||'reviewed',req.body?.adminNote||'',req.params.id]);res.json({ok:true});});
app.patch('/api/admin/reports/:id',auth,admin,async(req,res)=>{await q(`UPDATE reports SET status=$1,admin_note=$2 WHERE id=$3`,[req.body?.status||'reviewed',req.body?.adminNote||'',req.params.id]);res.json({ok:true});});
app.get('/api/admin/rooms',auth,admin,async(req,res)=>res.json(await q(`SELECT * FROM rooms ORDER BY id`)));
app.post('/api/admin/rooms',auth,admin,async(req,res)=>{const {name,description,duration,cameraRequired}=req.body||{};if(!name)return res.status(400).json({error:'Room name required'});const r=await one(`INSERT INTO rooms(name,description,duration,camera_required) VALUES($1,$2,$3,$4) RETURNING *`,[name,description||'',Number(duration)||50,!!cameraRequired]);res.json(r);});
app.patch('/api/admin/rooms/:id',auth,admin,async(req,res)=>{const r=await one(`SELECT * FROM rooms WHERE id=$1`,[req.params.id]);if(!r)return res.status(404).json({error:'Room not found'});const x=await one(`UPDATE rooms SET name=$1,description=$2,duration=$3,camera_required=$4,active=$5 WHERE id=$6 RETURNING *`,[req.body?.name??r.name,req.body?.description??r.description,Number(req.body?.duration??r.duration),req.body?.cameraRequired==null?r.camera_required:!!req.body.cameraRequired,req.body?.active==null?r.active:!!req.body.active,r.id]);res.json(x);});

let razorpay=null;if(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET)razorpay=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});
app.post('/api/payments/order',auth,async(req,res)=>{if(!razorpay)return res.status(503).json({error:'Online payments are not configured. Please use offline membership during the pilot.'});const plan=req.body?.plan==='quarterly'?'quarterly':'monthly';const amount=plan==='quarterly'?65000:25000;const order=await razorpay.orders.create({amount,currency:'INR',receipt:`brs_${req.user.id}_${Date.now()}`});await q(`INSERT INTO payments(user_id,plan,amount,provider,provider_order_id,status) VALUES($1,$2,$3,'razorpay',$4,'created')`,[req.user.id,plan,amount,order.id]);res.json({order,key:process.env.RAZORPAY_KEY_ID});});
app.post('/api/payments/verify',auth,async(req,res)=>{if(!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:'Payments are not configured'});const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(razorpay_order_id+'|'+razorpay_payment_id).digest('hex');if(expected!==razorpay_signature)return res.status(400).json({error:'Payment signature verification failed'});const p=await one(`SELECT * FROM payments WHERE provider_order_id=$1 AND user_id=$2`,[razorpay_order_id,req.user.id]);if(!p)return res.status(404).json({error:'Payment order not found'});const months=p.plan==='quarterly'?3:1,expiry=addMonths(new Date(),months);await q(`UPDATE payments SET provider_payment_id=$1,status='paid' WHERE id=$2`,[razorpay_payment_id,p.id]);await q(`UPDATE users SET plan=$1,membership_status='active',membership_expires=$2 WHERE id=$3`,[p.plan,expiry,req.user.id]);res.json({ok:true,expires:expiry});});
app.post('/api/payments/webhook',express.raw({type:'application/json'}),(req,res)=>res.json({ok:true}));

io.use((socket,next)=>{try{const token=socket.handshake.auth?.token;if(!token)throw 0;socket.user=jwt.verify(token,JWT_SECRET);next();}catch{next(new Error('Invalid session'));}});
io.on('connection',socket=>{socket.on('room:join',async({roomId})=>{const room=await one(`SELECT * FROM rooms WHERE id=$1 AND active=true`,[roomId]);if(!room)return socket.emit('room:error','Room unavailable');const u=await safeUser(socket.user.id);if(!activeMembership(u))return socket.emit('room:error','Active membership required');const rid=String(roomId);if(!roomPeers.has(rid))roomPeers.set(rid,new Set());roomPeers.get(rid).add(socket.id);socket.join(rid);socket.data.roomId=rid;socket.emit('room:joined',{room,participants:roomPeers.get(rid).size});socket.to(rid).emit('peer:joined',{peerId:socket.id});io.to(rid).emit('room:count',{count:roomPeers.get(rid).size});});socket.on('webrtc:offer',({to,offer})=>io.to(to).emit('webrtc:offer',{from:socket.id,offer}));socket.on('webrtc:answer',({to,answer})=>io.to(to).emit('webrtc:answer',{from:socket.id,answer}));socket.on('webrtc:ice',({to,candidate})=>io.to(to).emit('webrtc:ice',{from:socket.id,candidate}));socket.on('room:leave',()=>leaveRoom(socket));socket.on('disconnect',()=>leaveRoom(socket));});
function leaveRoom(socket){const rid=socket.data.roomId;if(!rid)return;const set=roomPeers.get(rid);if(set){set.delete(socket.id);if(!set.size)roomPeers.delete(rid);else io.to(rid).emit('room:count',{count:set.size});}socket.to(rid).emit('peer:left',{peerId:socket.id});socket.leave(rid);socket.data.roomId=null;}
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log(`BRS Digital Library running on port ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
